"""One gate every ontology write passes, whichever surface asked for it.

Why this exists
---------------
`POST /ontology/expand` gates what it extracts: `expansion_schema.check_entry`
refuses an entry that mints a predicate, hand-types a truth value, redefines a
calibration constant or cites no paper. `POST /ontology/apply` gated *the path*
— `_ensure_allowed_target` confines the write to the two ontology roots — and
then appended `metta_block` **verbatim**. Nothing required that block to be the
one `/ontology/expand` produced, and nothing stopped it naming a curated file.

Measured on this checkout: a single unauthenticated request appending

    (= (evidence-confidence RCT_Human) 0.05)

to `epistemic_calibration.metta` re-tiers every human trial in the knowledge
base, permanently, for every subsequent caller on that deployment — and the
change is invisible in the response, which just says `applied: true`. The same
door takes an append large enough to push a curated file past
`PLN_MAX_KB_FILE_BYTES`, at which point the runtime silently stops loading it
and answers get quietly thinner rather than erroring.

So the gate here is three questions, asked of every write:

1. **Is this file yours to write?** Curated `.metta` files are the repository's
   reviewed content. Appends go to `CUSTOM_ONTOLOGY_DIR`; writing a curated
   file needs `PLN_ALLOW_CURATED_WRITES=1`, which an operator sets knowing what
   it means.
2. **Does the block clear the same schema gate the extractor clears?** The
   identical `check_entry` call, so the two doors cannot disagree about what
   the knowledge base will accept.
3. **Does the file stay loadable?** A file that grows past the KB size cap stops
   being read, and a write that silently un-loads a layer is worse than a
   refusal.

The Gradio "Apply to Ontology" button is mounted on the same ASGI app and is
reachable by anyone who can reach the API, so it calls this too.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from config import (
    CUSTOM_ONTOLOGY_DIR,
    ONTOLOGY_DIR,
    PLN_ALLOW_CURATED_WRITES,
    PLN_MAX_APPLY_BYTES,
    PLN_MAX_KB_FILE_BYTES,
)
from ontology.expansion_schema import GateFinding, check_entry
from ontology.inventory import RuntimeInventory


@dataclass
class OntologyWriteRefused(Exception):
    """A write this service will not perform, with the reason a caller needs."""
    code: str
    message: str
    findings: list[GateFinding] = field(default_factory=list)
    status_code: int = 422

    def __str__(self) -> str:
        return self.message

    def as_detail(self) -> dict:
        detail: dict = {"code": self.code, "message": self.message}
        if self.findings:
            detail["refusals"] = [f.as_dict() for f in self.findings]
        return detail


def is_curated(path: Path) -> bool:
    """True when `path` is one of the repository's reviewed ontology files.

    Curated means "lives directly in ONTOLOGY_DIR" — the repo root, which is
    where the runtime KB set is read from. A file under CUSTOM_ONTOLOGY_DIR is
    caller-generated by construction and is the intended landing place.
    """
    resolved = path.resolve(strict=False)
    custom = CUSTOM_ONTOLOGY_DIR.resolve(strict=False)
    if resolved.parent == custom:
        return False
    return resolved.parent == ONTOLOGY_DIR.resolve(strict=False)


def guard_ontology_write(
    target_path: Path,
    metta_block: str,
    *,
    inventory: Optional[RuntimeInventory] = None,
    schema_checked: bool = False,
    allow_curated: Optional[bool] = None,
) -> None:
    """Raise `OntologyWriteRefused` unless this append is safe to perform.

    Parameters
    ----------
    schema_checked:
        True when the block was produced by the extraction pipeline, whose
        entries already passed `check_entry` individually. The block is still
        size-checked and still may not touch a curated file; re-running the
        vocabulary gate over the assembled block would only re-derive an answer
        already known.
    allow_curated:
        Overrides `PLN_ALLOW_CURATED_WRITES`, for tests and for a caller that
        has its own authorisation story.
    """
    permitted = PLN_ALLOW_CURATED_WRITES if allow_curated is None else allow_curated
    if is_curated(target_path) and not permitted:
        raise OntologyWriteRefused(
            code="curated_file_is_read_only",
            message=(
                f"'{target_path.name}' is a curated ontology file: the rules, the "
                f"calibration constants and the evidence the service reasons from. "
                f"Appending to it changes every future answer for every caller, so "
                f"it is refused unless the operator sets PLN_ALLOW_CURATED_WRITES=1. "
                f"Write to a new file under {CUSTOM_ONTOLOGY_DIR.name}/ instead — it "
                f"is loaded the same way."
            ),
            status_code=403,
        )

    block_bytes = len(metta_block.encode("utf-8"))
    if block_bytes > PLN_MAX_APPLY_BYTES:
        raise OntologyWriteRefused(
            code="block_too_large",
            message=(
                f"metta_block is {block_bytes} bytes; at most {PLN_MAX_APPLY_BYTES} "
                f"per write."
            ),
        )

    existing = target_path.stat().st_size if target_path.exists() else 0
    if existing + block_bytes > PLN_MAX_KB_FILE_BYTES:
        raise OntologyWriteRefused(
            code="file_would_exceed_kb_cap",
            message=(
                f"'{target_path.name}' would reach {existing + block_bytes} bytes, "
                f"past the {PLN_MAX_KB_FILE_BYTES}-byte cap above which the runtime "
                f"stops loading a file (hyperon 0.2.10 aborts on large spaces). The "
                f"write is refused rather than silently removing the file from the "
                f"knowledge base. Split the entries across files."
            ),
        )

    if schema_checked:
        return

    # NOT `identifier_text=metta_block`. That parameter is for the caller's own
    # statement of where an entry came from — the paper's text on the extraction
    # path. Passing the block as its own provenance lets a `;;` header line
    # satisfy the mandatory-identifier rule, and a comment is not loaded into
    # the space, so nothing in the knowledge base would carry it. On this path
    # the block IS all there is, so the identifier has to be in an atom.
    findings = check_entry(metta_block, inventory=inventory)
    if findings:
        raise OntologyWriteRefused(
            code="block_failed_schema_gate",
            message=(
                "The block does not pass the same schema gate POST /ontology/expand "
                "applies, so it was not written. Each refusal below names the text "
                "that triggered it."
            ),
            findings=findings,
        )
